name: "Update latest GeForce Now games"
on:
  schedule:
    - cron: "0 16 * * *" # Every day at 9am PST, not accounting for DST
  workflow_dispatch: # On manual run
jobs:
  update_games:
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch games from Nvidia's API and then save them to latest-geforce-now-games.json"
        uses: arcataroger/fetch-geforce-now-games@master # This runs a simple JS to fetch the games, then commits them to a file in this repo
