name: "Fetch games and commit"
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch games
        uses: arcataroger/fetch-geforce-now-games@0.0.1